Add boilerplate
PipeWebMonetization/plugin-wordpress pull request #2
Opened 2022-02-09 20:28 UTC by GabrielTomonariDev

## What does this Pull Request Do?
- Initialize the plugin work tree with a code boilerplate

## Where should the reviewer start?
- Read the documentation from the original [repo](https://github.com/TukuToi/better-wp-plugin-boilerplate)
- Read the new files

## How is this tested?
- Go to `wp-admin/plugins.php` and activate the plugin
- Check if the message is successful

## Background

## Images/Screenshots

## Related issue(s)

## Questions/Comments

2022-02-09 22:34 UTC, pivagabriel commented on src/pipe-web-monetization.php
> + * Plugin Name:       Pipe Web Monetiation
Change 'Monetiation' to 'Monetization'

2022-02-09 22:36 UTC, pivagabriel requested changes
Fix plugin name

2022-02-10 13:36 UTC, andreytdl commented on src/admin/css/pipe-web-monetization-admin.css
> + */
Missing an empty line at the end of this file

2022-02-10 13:56 UTC, GabrielTomonariDev commented on src/pipe-web-monetization.php
> + * Plugin Name:       Pipe Web Monetiation
Thx

2022-02-10 14:00 UTC, andreytdl reviewed
Just some comments. Good job, bro!

2022-02-10 14:00 UTC, andreytdl commented on src/public/css/pipe-web-monetization.css
> + */
Missing empty line

2022-02-10 14:02 UTC, EijiTomonari commented on src/admin/css/pipe-web-monetization-admin.css
> + */
Nice

2022-02-10 14:41 UTC, pivagabriel approved these changes

2022-02-10 16:58 UTC, merged